### ISSUE TITLE
error in inference step

### ISSUE THREAD

**Issue by amiltonwong** [art-programmer/MASC#4]
Hi, @art-programmer , @chenliu-wustl ,

When I performance inference step,
`python inference.py --dataFolder=/media/root/WDdata/dataset/ScanNet --task=predict_cluster_write --split=val`

I got the following error
```
Traceback (most recent call last):
  File "inference.py", line 219, in <module>
    info = torch.load(filename)
  File "/root/anaconda3/envs/pytorch1.0/lib/python3.6/site-packages/torch/serialization.py", line 366, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/gruvi/Data/chenliu/ScanNet/scans//scene0568_00/scene0568_00_vh_clean_2.pth'

```

It seems file "scene0568_00_vh_clean_2.pth" is missing. Where could I download it?

THX!

**Comment by art-programmer** [comment]
Thanks for reporting this. It's indeed a bug. I just fixed it. Thanks a lot!
