### ISSUE TITLE
module 'sparseconvnet.SCN' has no attribute 'Metadata_3'

### ISSUE THREAD

**Issue by jyw777** [art-programmer/MASC#7]
Hi @art-programmer , @chenliu-wustl,
Thanks for your codes.

**When I trained the model, I  got the output like this:**
keyname=instance_normal_augment_2 task=train started
the number of images val 20
the number of images train 1201
the number of images 1201

**But after that, I got:**
Traceback (most recent call last):
  File "train.py", line 390, in <module>
    main(args)
  File "train.py", line 91, in main
    augmented_coords, augmented_colors, augmented_instances, _ = augmentation_model(coords[batch_index], faces[batch_index], colors[batch_index], instances[batch_index])
  File "/orion/u/jiayun/env/anaconda3/envs/sp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/orion/u/jiayun/downloads/MASC/models/instance.py", line 199, in forward
    voxel = self.input_layer((all_coords, all_values))
  File "/orion/u/jiayun/env/anaconda3/envs/sp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/orion/u/jiayun/downloads/MASC/src/sparseconvnet/sparseconvnet/ioLayers.py", line 49, in forward
    self.dimension),
  File "/orion/u/jiayun/downloads/MASC/src/sparseconvnet/sparseconvnet/metadata.py", line 17, in Metadata
    return getattr(sparseconvnet.SCN, 'Metadata_%d'%dim)()
**AttributeError: module 'sparseconvnet.SCN' has no attribute 'Metadata_3'**

Do you have any idea about that?
Thanks.

**Comment by art-programmer** [comment]
It seems to be an issue from the SparseConvNet code.

https://github.com/facebookresearch/SparseConvNet/issues/56

**Comment by jyw777** [comment]
It is probably because I have downloaded Sparseconv repo before and now I download the MASC which also contain Sparseconv repo. When I remove the Sparseconv repo I downloaded before, I can run the code.

Thank you !
